// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"database/sql"
)

type Message struct {
	Messageid  int32
	Threadid   sql.NullInt32
	Text       sql.NullString
	Timestamp  sql.NullTime
	Sentbyuser sql.NullBool
	Userid     sql.NullInt32
}

type Thread struct {
	Threadid    int32
	Name        string
	Temperature sql.NullInt32
	Typingspeed sql.NullInt32
	Userid      int32
}

type User struct {
	Userid   int32
	Username string
}
