// Code generated by sqlc. DO NOT EDIT.
// version: sqlc v1.27.0

namespace SE2.Infrastructure.Persistence.SQLc

open System
open Npgsql

type User = 
    {
        Userid : int
        Username : string
    }

type Thread = 
    {
        Threadid : int
        Name : string
        Temperature : int option
        Typingspeed : int option
        Userid : int
    }

type Message = 
    {
        Messageid : int
        Threadid : int option
        Text : string option
        Timestamp : DateTime option
        Sentbyuser : bool option
        Userid : int option
    }

