// Code generated by sqlc. DO NOT EDIT.
// version: sqlc v1.27.0
// for nuget package Npgsql.FSharp --version 5.7.0

namespace SE2.Infrastructure.Persistence.SQLc

open System
open Npgsql
open Npgsql.FSharp
open SE2.Infrastructure.Persistence.SQLc.Readers

module Sqls = 

  [<Literal>]
  let getAllUsers =
    """
    SELECT userid, username FROM users
  """

  [<Literal>]
  let createUser =
    """
    INSERT INTO users (username)
VALUES (@username)
RETURNING userid, username
  """

  [<Literal>]
  let deleteUser =
    """
    DELETE FROM users
WHERE userid = @userid
  """

[<RequireQualifiedAccessAttribute>]
type DB (conn: string) =
  // https://www.connectionstrings.com/npgsql

  member this.getAllUsers  () =

    conn
    |> Sql.connect
    |> Sql.query Sqls.getAllUsers
    |> Sql.execute userReader

  member this.createUser  (username: string) =

    let parameters = [ ("username", Sql.string username) ]
    
    conn
    |> Sql.connect
    |> Sql.query Sqls.createUser
    |> Sql.parameters parameters
    |> Sql.executeRow userReader

  member this.deleteUser  (userid: int) =

    let parameters = [ ("userid", Sql.int userid) ]
    
    conn
    |> Sql.connect
    |> Sql.query Sqls.deleteUser
    |> Sql.parameters parameters
    |> Sql.executeNonQuery

