// Code generated by sqlc. DO NOT EDIT.
// version: sqlc v1.27.0
// for nuget package Npgsql.FSharp --version 5.7.0

namespace SE2.Infrastructure.Persistence.SQLc

open System
open Npgsql
open Npgsql.FSharp

module Readers =

    let userReader (r: RowReader) : User = { User.Userid = r.int "userid" ; Username = r.string "username" }

